# Generated by Django 5.1.1 on 2024-11-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_items_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
