# Generated by Django 5.1.1 on 2024-11-22 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_balance_remaining_balance_balance_spend_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.balance')),
            ],
        ),
    ]
