# Generated by Django 5.1.1 on 2024-11-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='remaining_balance',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
