# Generated by Django 5.1.1 on 2024-11-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_balance_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
