# Generated by Django 5.1.1 on 2024-11-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
