# Generated by Django 5.1.1 on 2024-11-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_balance_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='count',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
